name: workflowtest

on:
  workflow_dispatch:
    inputs:
       tagname:
          required: true
          type: string
jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
        script: github.rest.git.createRef({owner: context.repo.owner, repo: context.repo.repo, ref: 'refs/tags/${{ inputs.tagname }}', sha: context.sha })
